import type { Metadata } from "next";
import localFont from 'next/font/local';
import "./globals.css";
import { ThemeProvider } from "@/context/ThemeContext";
import HeaderNav from "@/components/HeaderNav";
import { Toaster } from "@/components/ui/sonner"



const testMetricFont = localFont({
  src: [
    { path: '../public/fonts/TestMetric-Thin.otf', weight: '100', style: 'normal' },
    { path: '../public/fonts/TestMetric-Light.otf', weight: '300', style: 'normal' },
    { path: '../public/fonts/TestMetric-Medium.otf', weight: '500', style: 'normal' },
    { path: '../public/fonts/TestMetric-Semibold.otf', weight: '600', style: 'normal' },
    { path: '../public/fonts/TestMetric-Bold.otf', weight: '700', style: 'normal' },
    { path: '../public/fonts/TestMetric-Black.otf', weight: '900', style: 'normal' },
  ],
  display: 'swap',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${testMetricFont.className} ${testMetricFont.className} antialiased`}
      >
        <ThemeProvider>
        <HeaderNav />
          {children}
          <Toaster />
        </ThemeProvider>
      </body>
    </html>
  );
}
